import fs from 'node:fs';
import path from 'node:path';
import { CLI_ALIASES, CLI_BIN } from './name.js';

/** First-word verbs and aliases. Keep in sync with parseKitArgv. */
export const KIT_TOP_LEVEL_COMMANDS = [
  'init',
  'doctor',
  'mcp',
  'audit',
  'scan',
  'validate',
  'eval',
  'export-rules',
  'metrics',
  'verify',
  'sync',
  'measure-context',
  'debug-board',
  'debug-ci',
  'check',
  'ontology',
  'memory',
  'model',
  'site',
  'commit-msg',
  'completion',
  'help'
] as const;

export const KIT_NESTED_COMMANDS: Record<string, readonly string[]> = {
  eval: ['run', 'watch', 'report', 'ci', 'shadow', 'dataset'],
  ontology: ['generate', 'check'],
  memory: ['lint'],
  model: ['resolve'],
  site: ['assemble'],
  completion: ['zsh', 'bash']
};

export const KIT_COMPLETION_SHELLS = ['zsh', 'bash'] as const;
export type KitCompletionShell = (typeof KIT_COMPLETION_SHELLS)[number];

export function isCompletionShell(value: string | undefined): value is KitCompletionShell {
  return value !== undefined && (KIT_COMPLETION_SHELLS as readonly string[]).includes(value);
}

export function listMcpProfileNames(repoDir: string): string[] {
  const dir = path.join(repoDir, 'mcps', 'profiles');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .map((name) => name.replace(/\.json$/, ''))
    .sort();
}

export interface RenderCompletionOptions {
  mcpProfiles?: readonly string[];
}

function zshWords(values: readonly string[]): string {
  return values.map((value) => value.replaceAll("'", "'\\''")).join(' ');
}

export function renderZshCompletion(opts: RenderCompletionOptions = {}): string {
  const bins = [CLI_BIN, ...CLI_ALIASES];
  const cmds = zshWords(KIT_TOP_LEVEL_COMMANDS);
  const profiles = zshWords(opts.mcpProfiles ?? []);
  const nestedCases = Object.entries(KIT_NESTED_COMMANDS)
    .map(([cmd, subs]) => `    ${cmd}) _values '${cmd}' ${zshWords(subs)} ;;`)
    .join('\n');
  const mcpCase =
    profiles.length > 0
      ? `    mcp) _values 'profile' ${profiles} ;;\n`
      : '';

  return `#compdef ${bins.join(' ')}
# Generated by ${CLI_BIN} completion zsh

_wk() {
  local -a cmds
  cmds=(${cmds})
  if (( CURRENT == 2 )); then
    compadd -a cmds
    return
  fi
  case \${words[2]} in
${nestedCases}
${mcpCase}    doctor)
      _arguments \\
        '--write[fill missing community files]' \\
        '--owned[GitHub sources you admin]' \\
        '--scan[local worktree root]:dir:_files -/' \\
        '--class[repo class]:class:(kit product dns site template)' \\
        '--hook[install git hooks on owned repos]' \\
        '--login[GitHub login]:login:' \\
        '*:dir:_files -/'
      ;;
  esac
}

compdef _wk ${bins.join(' ')}
`;
}

export function renderBashCompletion(opts: RenderCompletionOptions = {}): string {
  const bins = [CLI_BIN, ...CLI_ALIASES];
  const cmds = KIT_TOP_LEVEL_COMMANDS.join(' ');
  const nested = Object.entries(KIT_NESTED_COMMANDS)
    .map(([cmd, subs]) => `    ${cmd}) opts="${subs.join(' ')}" ;;`)
    .join('\n');
  const mcpLine =
    (opts.mcpProfiles?.length ?? 0) > 0
      ? `    mcp) opts="${(opts.mcpProfiles ?? []).join(' ')}" ;;\n`
      : '';

  return `# Generated by ${CLI_BIN} completion bash
_wk() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local cmd="\${COMP_WORDS[1]}"
  local opts=""
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${cmds}" -- "\$cur") )
    return
  fi
  case "\$cmd" in
${nested}
${mcpLine}  esac
  COMPREPLY=( $(compgen -W "\$opts" -- "\$cur") )
}
${bins.map((bin) => `complete -F _wk ${bin}`).join('\n')}
`;
}

export function renderCompletion(shell: KitCompletionShell, opts: RenderCompletionOptions = {}): string {
  return shell === 'zsh' ? renderZshCompletion(opts) : renderBashCompletion(opts);
}
